spring.application.name=SpringAiDemo
<<<<<<< HEAD
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# Gemini / image generation
#gemini.api-key=${GEMINI_API_KEY}
=======
spring.ai.openai.api-key=YOUR_API_KEY    //i used groq api key since open ai api key is paid
spring.ai.openai.base-url=https://api.groq.com/openai/
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

#gemini.api-key=YOUR_API_KEY //if we use open ai paid api key this is not require it has image model in it
>>>>>>> 1966c1b8194a7b2ce9d1c5062e07a20692d4fabd
#gemini.base-url=https://generativelanguage.googleapis.com/v1beta
#gemini.image.model=gemini-2.5-flash-image
#spring.ai.image.model-provider=google-genai